### ISSUE TITLE
Artifacts use file name, not json name property

### ISSUE THREAD

**Issue by MikeMartin180** [liprec/vsts-publish-adf#12]
Hello, 

When creating artifacts, e.g. LinkedServices, it uses the file name.

Line 380 in deploy-adf-json.psm1 - `$linkedServiceName =  ($JsonFile.Name).Replace('.json', '')`

Ideally, it should use the name property from within the json.

$linkedServiceName = ($JsonFile | ConvertFrom-Json).name

Unfortunately, due to linked service nesting (when using Azure Key Vault), we need to deploy Key Vault first as it's a dependency. The way we have of doing this is to put a number at the start of the file name in the VSTS repo to enforce the order they are deployed. But we do not want this numbering to be included in the deployed artifacts

Many Thanks,
Mike.

**Comment by liprec** [comment]
Your requirement will be added in the v2 version of the extension.
This version is almost done (need some sanity checks and code cleanups) and will use the REST APIs instead of the PowerShell commands.

**Comment by liprec** [comment]
I have published the V2 versions of the tasks in preview, so feel free to test if it is working regarding this issue/.

**Comment by patpicos** [comment]
related issue logged https://github.com/liprec/vsts-publish-adf/issues/15
