### ISSUE TITLE
Azure Data Factory Trigger Pipeline (Preview) - Ability to pass parameters

### ISSUE THREAD

**Issue by patpicos** [liprec/vsts-publish-adf#16]
Hi

It would be good to be able to pass in parameters into the pipeline. Either as a JSON object or key value pairs.

**Comment by liprec** [comment]
Have to dig into this, but it is a good enhancement.

**Comment by patpicos** [comment]
Here's a good starting code to submit a pipeline. I leveraged the following documentation:
https://docs.microsoft.com/en-us/azure/data-factory/quickstart-create-data-factory-powershell#create-a-pipeline-run
https://docs.microsoft.com/en-us/azure/data-factory/quickstart-create-data-factory-powershell#monitor-the-pipeline-run
https://docs.microsoft.com/en-us/powershell/module/azurerm.datafactoryv2/Invoke-AzureRmDataFactoryV2Pipeline?view=azurermps-6.9.0


```powershell
Params:
	[string] $resourceGroupName
    [string] $dataFactoryName 
    [string] $pipelineName
    [optional] [string] $pipelineParameters  (likely passed as a JSON string)
    [optional]  [boolean] $waitForCompletion = $false
    
    $pipelineParametersDict = $pipelineParameters | convertFrom-json


$DataFactory = Get-AzureRmDataFactoryV2 -DataFactoryName $dataFactoryName -ResourceGroupName $resourceGroupName
if (-not $DataFactory) {
    throw "Invalid Factory provided. Data Factory $DataFactory"
}
$Pipeline = Get-AzureRmDataFactoryV2Pipeline -ResourceGroupName $resourceGroupName -DataFactoryName $dataFactoryName -Name $pipeLineName
if (-not $$pipeline) {
    throw "Pipeline not found. Pipeline provided: $pipeLineName"
}
if ($pipelineParameters) {
    #Submit with parameters
    $RunId = Invoke-AzureRmDataFactoryV2Pipeline -DataFactoryName $DataFactory.DataFactoryName -ResourceGroupName $resourceGroupName -PipelineName $DFPipeLine.Name -Parameter $pipelineParametersDict
} else {
    #Submit w/o parameters
    $RunId = Invoke-AzureRmDataFactoryV2Pipeline -DataFactoryName $DataFactory.DataFactoryName -ResourceGroupName $resourceGroupName -PipelineName $DFPipeLine.Name
}

if ($runId) {
    Write-host "Successfully submitted $pipeLineName submitted to $dataFactorName. Run Id: $runId"
} else {
    throw "Pipeline $pipeLineName failed to submit"
}

if ($waitForCompletion) {
    while ($True) {
        $Run = Get-AzureRmDataFactoryV2PipelineRun -ResourceGroupName $ResGrp.ResourceGroupName -DataFactoryName $DataFactory.DataFactoryName -PipelineRunId $RunId

        if ($Run) {
            if ($run.Status -ne 'InProgress') {
                Write-Output ("Pipeline run finished. The status is: " +  $Run.Status)
                $Run
                break
            }
            Write-Output  "Pipeline is running...status: InProgress"
        }

        Start-Sleep -Seconds 10
    }  
    if ($run.Status -ne "Successful") {
        throw "Pipeline $pipeLineName failed"
    }
}

```

**Comment by patpicos** [comment]
I am not fully familiar w/ the VSTS plugin framework to raise errors...so i used throw to keep things simple.

**Comment by patpicos** [comment]
FYI - I am almost done creating the powershell script. 
will share after

**Comment by patpicos** [comment]
Here you go, 

```powershell
param (
    [parameter(Mandatory=$true)] [string] $resourceGroupName , 
    [parameter(Mandatory=$true)] [string] $dataFactoryName ,
    [parameter(Mandatory=$true)] [string] $pipelineName , 
    [string] $pipelineParameters,
    [boolean] $waitForCompletion = $false
)

$DataFactory = Get-AzureRmDataFactoryV2 -DataFactoryName $dataFactoryName -ResourceGroupName $resourceGroupName -ErrorAction ignore
if (-not $DataFactory) {
    throw "Invalid Factory provided. Data Factory $DataFactoryName not found."
}

$Pipeline = Get-AzureRmDataFactoryV2Pipeline -ResourceGroupName $resourceGroupName -DataFactoryName $dataFactoryName -Name $pipeLineName
if (-not $pipeline) {
    throw "Pipeline not found. Pipeline provided: $pipeLineName"
}
if ($pipelineParameters) {
    #Submit with parameters
    $hashtable = @{}
    (ConvertFrom-Json $pipelineParameters).psobject.properties | Foreach { $hashtable[$_.Name] = $_.Value }
    $RunId = Invoke-AzureRmDataFactoryV2Pipeline -DataFactoryName $DataFactory.DataFactoryName -ResourceGroupName $resourceGroupName -PipelineName $PipeLine.Name -Parameter $hashtable
} else {
    #Submit w/o parameters
    $RunId = Invoke-AzureRmDataFactoryV2Pipeline -DataFactoryName $DataFactory.DataFactoryName -ResourceGroupName $resourceGroupName -PipelineName $PipeLine.Name
}

if ($runId) {
    Write-host "Successfully submitted $pipeLineName submitted to $dataFactoryName. Run Id: $runId"
} else {
    throw "Pipeline $pipeLineName failed to submit"
}

if ($waitForCompletion) {
    while ($True) {
        $Run = Get-AzureRmDataFactoryV2PipelineRun -ResourceGroupName $ResourceGroupName -DataFactoryName $DataFactory.DataFactoryName -PipelineRunId $RunId

        if ($Run) {
            if ($run.Status -ne 'InProgress') {
                Write-Output ("Pipeline run $RunId finished. The status is: " +  $Run.Status)
                $Run
                break
            }
            Write-Output  "Pipeline is running...status: InProgress"
        }

        Start-Sleep -Seconds 10
    }  
    if ($run.Status -ne "Successful") {
        $run
        throw "Pipeline $pipeLineName failed"
    }
}
```

**Comment by liprec** [comment]
@patpicos, the pipeline parameter option is available to the Trigger Pipeline task.

**Comment by garimasingh15** [comment]
@liprec , May I ask you to put up an example on how to use this parameter feature in the following cases: a. Pass parameters to only a few pipelines 
b. The format in which the parameter values need to be passed

**Comment by 797930** [comment]
> Here you go,
> 
> ```powershell
> param (
>     [parameter(Mandatory=$true)] [string] $resourceGroupName , 
>     [parameter(Mandatory=$true)] [string] $dataFactoryName ,
>     [parameter(Mandatory=$true)] [string] $pipelineName , 
>     [string] $pipelineParameters,
>     [boolean] $waitForCompletion = $false
> )
> 
> $DataFactory = Get-AzureRmDataFactoryV2 -DataFactoryName $dataFactoryName -ResourceGroupName $resourceGroupName -ErrorAction ignore
> if (-not $DataFactory) {
>     throw "Invalid Factory provided. Data Factory $DataFactoryName not found."
> }
> 
> $Pipeline = Get-AzureRmDataFactoryV2Pipeline -ResourceGroupName $resourceGroupName -DataFactoryName $dataFactoryName -Name $pipeLineName
> if (-not $pipeline) {
>     throw "Pipeline not found. Pipeline provided: $pipeLineName"
> }
> if ($pipelineParameters) {
>     #Submit with parameters
>     $hashtable = @{}
>     (ConvertFrom-Json $pipelineParameters).psobject.properties | Foreach { $hashtable[$_.Name] = $_.Value }
>     $RunId = Invoke-AzureRmDataFactoryV2Pipeline -DataFactoryName $DataFactory.DataFactoryName -ResourceGroupName $resourceGroupName -PipelineName $PipeLine.Name -Parameter $hashtable
> } else {
>     #Submit w/o parameters
>     $RunId = Invoke-AzureRmDataFactoryV2Pipeline -DataFactoryName $DataFactory.DataFactoryName -ResourceGroupName $resourceGroupName -PipelineName $PipeLine.Name
> }
> 
> if ($runId) {
>     Write-host "Successfully submitted $pipeLineName submitted to $dataFactoryName. Run Id: $runId"
> } else {
>     throw "Pipeline $pipeLineName failed to submit"
> }
> 
> if ($waitForCompletion) {
>     while ($True) {
>         $Run = Get-AzureRmDataFactoryV2PipelineRun -ResourceGroupName $ResourceGroupName -DataFactoryName $DataFactory.DataFactoryName -PipelineRunId $RunId
> 
>         if ($Run) {
>             if ($run.Status -ne 'InProgress') {
>                 Write-Output ("Pipeline run $RunId finished. The status is: " +  $Run.Status)
>                 $Run
>                 break
>             }
>             Write-Output  "Pipeline is running...status: InProgress"
>         }
> 
>         Start-Sleep -Seconds 10
>     }  
>     if ($run.Status -ne "Successful") {
>         $run
>         throw "Pipeline $pipeLineName failed"
>     }
> }
> ```

How to pass the pipelineParameters?
