### ISSUE TITLE
ADF V1 Json files not deployed

### ISSUE THREAD

**Issue by saishankar16** [liprec/vsts-publish-adf#17]
I created a release pipeline in visual studio online and added the Azure data factory deployment task downloaded from here, but json are not deployed even after the release got succeeded.
@liprec

**Comment by liprec** [comment]
Sorry, I missed you issue, but is it possible to add the `system.debug` variable to you release pipeline and set it to `true` to enable full logging?

**Comment by saishankar16** [comment]
Can you help me with any of videos, I can understand much. I am so new to VSTS. I have my sample json files in my repository and am failing somewhere in the middle.

**Comment by liprec** [comment]
Hands-on tutorial is still on my backlog, see liprec/azurebi-docs#8 for more details and progress.
