### ISSUE TITLE
MSI  authentication is not correctly deployed

### ISSUE THREAD

**Issue by mfernee** [liprec/vsts-publish-adf#20]
When deploying a web activity with authentication type MSI, the resource stays blank.

Can you please also update the resource. Thanks :-)

[WebActivity.json.txt](https://github.com/liprec/vsts-publish-adf/files/2648478/WebActivity.json.txt)

**Comment by liprec** [comment]
Does it work if you deploy it manual via the UI and the `Code` option?
The extension only deploys the raw JSON to the API without any alteration/validation, the same as the UI is doing.
