### ISSUE TITLE
V2 version of this plugg in doesn't have option to select ADFV1/V2. 

### ISSUE THREAD

**Issue by amithradharapu** [liprec/vsts-publish-adf#21]
Hi Team,

V2 version of this plug in doesn't have option to select ADFV1/V2. It is there in V1 version.

Thanks,
Amith Radharapu

**Comment by liprec** [comment]
This is intended, but both versions of the plugin will be available.
Are there any things specific that you need from the V2 version to work with ADFv1?

**Comment by amithradharapu** [comment]
Can V2 version of this plug in handle ADFV1 deployment.? We would like to  use V2 version for both ADFV1 and ADFV2 deployment with in single release pipeline.
