### ISSUE TITLE
Stop/Start triggers task fail intermittantly

### ISSUE THREAD

**Issue by Prashanth-PS** [liprec/vsts-publish-adf#22]
Hi,
I was using this task for some time without any issues. 
Recently it started throwing up errors intermittantly (Sometimes it works and sometimes it doesn't) :
 ##[error]Unable to find environment with name 'AzureCloud'
##[error]There was an error with the service principal used for the deployment.

And also we are unable to move this task into a task group.

Could this be fixed at the earliest please. 
Regards,
Prashanth PS

**Comment by liprec** [comment]
Looking at the error messages it looks like there is something wrong with the connection between Azure DevOps and Azure.
Can you validate that the service principle of the 'AzureCloud' is still valid?
