### ISSUE TITLE
Azure Data Factory Delete Items

### ISSUE THREAD

**Issue by rajeevkarn** [liprec/vsts-publish-adf#23]
Hi 

The delete task - Azure Data Factory Delete Items - has random behaviour.
1- It was not able to find piplelines  for some piplines.
2- For a pipline filter - it once delted 16 pipleine only - in next run it deleted 11 pipeline and in yest another run it deleted only 6 pipeline - Number of pipleines were more than 50.
3- the delete task can delete only 50 datasets in one task.

Regards
Rajeev

**Comment by liprec** [comment]
Thanks for the feedback. Is it possible that there are any dependancies between the pipelines that causes to delete some pipelines not directly?
For the maximum of 50 items: I have to look what is causing this.

**Comment by rajeevkarn** [comment]
I have pipelines named with 01,02 ,03 prefix where 01 can be used in 02 and
02 can be used in 03.

when I try to delete with filter 03* first and then 02* and then 01* it
does not work.

I guess the problem is with it not being able to filter properply.

and I guess this happens a bit randomly -
- When I got the number of piplelines reduced to about 30 then the filter
was working OK for 1 or 2 time but not always
- when I have more than 80 pipeline then it does not find all pipelines
with the applied filter.

if you would like then I can show you with screen share.

Regards
Rajeev
