### ISSUE TITLE
Handling dependent pipelines

### ISSUE THREAD

**Issue by garimasingh15** [liprec/vsts-publish-adf#25]
We have multiple pipelines which are dependent on other pipelines which needs that the dependencies get deployed before the dependants. Is there a way this can be handled through the Deploy JSON files Azure Data Factory task in Azure DevOps

**Comment by liprec** [comment]
The only way to do this s either split it in multiple steps or by prefixing the filenames with the definitions, eg. 00_.

**Comment by garimasingh15** [comment]
@liprec Thank you for the response. I guess the same would have to be done for Deleting the pipelines as well.

**Comment by punith305** [comment]
Are all the pipelines deployed at once parallel or sequential based on alphabetic order

**Comment by liprec** [comment]
@punith305: the files are processed in parallel with a default maximum of 5 threads. You can change the number of threads by yourself via the advanced section. 
If you need a certain dependency you need to create it yourself by using multiple tasks

**Comment by neilmiaowang** [comment]
is it possible to reverse the order on deletion? so the deployment is by alphabetic ascending order, deletion is by alphabetic descending order.

**Comment by liprec** [comment]
@neilmiaowang thanks for the suggestion and I will include 'sorting orders' in the task for a next release.

**Comment by liprec** [comment]
The current version (v2.3.3) contains support for the detection of pipeline/linked service dependencies in combination of parallel task execution. You can add `detectDependancy: true` to your pipeline definition to enable the detection.
