### ISSUE TITLE
AzureRM.DataFactoryV2 module is older version

### ISSUE THREAD

**Issue by syedhamjath** [liprec/vsts-publish-adf#26]
Hi,
When using folder property in Pipeline JSON file, pipeline are not created in given folder. When I tried using updated AzureRM.DataFactoryV2 I'm able to deploy to required folder. 
Therefore, It would be great if you updated all reference PowerShell module to so that we can still continue to use this task.

```
{
"name": "FileToSQLTableTemplate",
"properties": {
.....
	"folder": {
		"name": "Test Pipelines"
	}
}
```

Thanks
Syedhamjath Syedmansur

**Comment by liprec** [comment]
Did you try the V2 version of the tasks?

**Comment by syedhamjath** [comment]
Yes, I have tried using V2 cmdlet and this issue is resolved after upgrading module to new version
