### ISSUE TITLE
Azure Data Factory Deployment with Integration Service as Parameter

### ISSUE THREAD

**Issue by SudhirKumarTfL** [liprec/vsts-publish-adf#27]
We have been trying to Queue a Build to deploy Data Factory V2 which uses Integration Runtime. When we create this build, it asks for parameters like Subscription, Resource Group Name, data Factory Name, Version, Path to Linked Services, Path to Datasets, Path to Pipelines. 

When we queue this build, it throws an error below:
Error Code: InputIsMalformedDetailed
Error Message: Input is malformed. Reason: Could not get integration runtime details for integrationRuntimeSFTP2

This is the Integration Runtime we use for a SFTP Linked Service.

Can someone advise how to do this or are there any other plugin we can use?

**Comment by liprec** [comment]
Are you using the V2 verwion of the tasks?
