### ISSUE TITLE
Azure Data Factory Pipelines Manage - Not able to find the datafactory under the resouce group

### ISSUE THREAD

**Issue by Kotachandrasekhara** [liprec/vsts-publish-adf#28]
I'm trying to use "Azure Data Factory Pipelines Manage" deployment step, however it is failing to find the data factory under the resource group. Actually, the ADF is present in that particular resource group 
 
2019-03-19T13:59:13.8880345Z ##[error]HTTP Status Code: NotFound
Error Code: ResourceNotFound
Error Message: The Resource 'Microsoft.DataFactory/dataFactories/*******' under resource group 'DEV*****RG' was not found.
Request Id: d88a1d8c-6812-49a4-aa01-a9b23d7f0987
Timestamp (Utc):03/19/2019 13:59:13
2019-03-19T13:59:13.9038066Z ##[section]Finishing: Set pipelines to 'suspend' in intplfadf

**Comment by liprec** [comment]
(Sorry for the late response)
Does the service account used by Azure DevOps have enough rights to 'see' the data factory?

**Comment by Kotachandrasekhara** [comment]
Hello Liprec, Yes it is having full access and Togger triggers step is working fine with this access, but deployment is not working.

**Comment by pdeveau** [comment]
I have similar issue, NB: triggers stop/start works just fine using same Azure Resource Manager Subscription
