### ISSUE TITLE
Error in ADF v2 deployment plugin - Unable to deserialize the response

### ISSUE THREAD

**Issue by veswesvaran** [liprec/vsts-publish-adf#29]
Hi @liprec ,

I used the plugin to deploy the ADFv2 in Release pipeline. I have created the build and provided the artifact path in the pipeline configuration. Yet, after deleting the existing pipeline and datasets the new ones are not getting deployed.
Instead we are getting the error "Unable to deserialize the response"

What is the reason behind this error. Could you please assist?
![adf](https://user-images.githubusercontent.com/48989290/55075564-361c2080-508b-11e9-85ac-14e76c25e5fb.png)

Hoping for a swift response

**Comment by veswesvaran** [comment]
@liprec  adding to the above point, I have made some troubleshoots where it is mentioned that the issue might occur due to Old Azure RM profile. Refer link - https://social.msdn.microsoft.com/Forums/vstudio/en-US/5e62c607-0e25-4e97-b343-8b45c7a280f0/azure-powershell-quotunable-to-deserialize-the-responsequot?forum=azurescripting

**Comment by liprec** [comment]
Can you try the V2 version of the tasks? These tasks are using the direct ADF REST API and are working independent of profile modules.

**Comment by veswesvaran** [comment]
Hi Jan,

Thanks for coming back. I have tried v2 version of the plugin as well. But it didnt help. I got the same error.

Regards,
Veswesvaran L

**Comment by liprec** [comment]
Just to make sure: can you post the error you are getting with the V2 (Preview) version of the tasks?
And can you add the variable `system.debug` with the value `true` to the pipeline to enable debugging?

**Comment by veswesvaran** [comment]
Hi Jan,

After adding debug. Config, the deployment went successful. Have you made nay changes in the source code of the plugin

Reagrds,
Veswesvaran

Regards,
Veswesvaran L

________________________________

**Comment by veswesvaran** [comment]
Hi Jan,

I was using the plugin to deploy the Adf v2 components. But it seems like the changes are reflected only in the Repo and not in actual datafactory. When i delete the pipeline and push to repo, and build as an artifact. I use this artifact as input to your plug in where changes are not being deployed.

Could you help?

Regards,
Veswesvaran

Regards,
Veswesvaran L

________________________________

**Comment by veswesvaran** [comment]
Hi Jan,

Could you please help us with the above issue

Regards,
Veswesvaran L

________________________________

**Comment by liprec** [comment]
Are getting any error/warning message with the variable `system.debug` set to `true`?

**Comment by veswesvaran** [comment]
Hi Jan,

I set that to true. But there are no errors. The release is succeeded but the adf is not deployed

Regards,
Veswesvaran L

________________________________

**Comment by liprec** [comment]
Are you sure that you didn't make any typo's in the folder/file parameters?

**Comment by veswesvaran** [comment]
Hi Jan,

Yes that is sure. The pipelines in GIT is getting changed. But it is not deployed in ADF v2

Regards,
Veswesvaran L

________________________________

**Comment by liprec** [comment]
It looks to me that there is nothing deployed somehow. And the most common issue is that the file parameters are not valid. Can you try selecting one distinct file?

![image](https://user-images.githubusercontent.com/12474072/60026268-895a3b00-969b-11e9-96eb-18ed021976b5.png)

**Comment by veswesvaran** [comment]
Hi Jan,

Here i provide the build artifact path of the datafactory.

Where it has list of components to be deployed.

Regards,
Veswesvaran L

________________________________

**Comment by liprec** [comment]
If the task finds any definitions (*.json) in the path it will log the number of definitions found with the type.
Do you see such a message, like `Found 2 dataset(s) definitions.`?

**Comment by veswesvaran** [comment]
Hi Jan,

Yes it is derecting the jasons correctly. But the problem is it is not reflected in ADF.

Really confused what is happening behind.

Regards,
Veswesvaran L

________________________________

**Comment by liprec** [comment]
I just tested it myself and a successful run should look similar like below.
Does uploading the json definition via the 'authoring' tool work? (using the `code` option of a new dataset)
![image](https://user-images.githubusercontent.com/12474072/60097191-2cba5700-9753-11e9-9d22-d0d7d2cb5915.png)

**Comment by veswesvaran** [comment]
Hi Jan,

Yes I am getting the above results. Yet it is not updated in the ADF V2.

Regards,
Veswesvaran L

________________________________

**Comment by liprec** [comment]
Sorry, but I am also lost what is causing this. Maybe you could contact me offline (mail@datascenarios.nl) to schedule some alternative way to look into this issue.

**Comment by veswesvaran** [comment]
Sure, shall we have a skype call by this weekend if possible?

Regards,
Veswesvaran L

________________________________

**Comment by liprec** [comment]
Fine with me, but let's discuss the details via email.

**Comment by aksalian** [comment]
Was this issue resolved?

**Comment by veswesvaran** [comment]
yes, the issue got resolved. thank you

Get Outlook for Android<https://aka.ms/ghei36>
________________________________
