### ISSUE TITLE
Add runId output to trigger jobs

### ISSUE THREAD

**Issue by pjeannet-dior** [liprec/vsts-publish-adf#37]
Hello,

First of all thank you for the plugin! 
I'm currently trying to monitor the status of some pipeline that I have triggered but I need the `runId` generated at trigger time.
What would it take to catch the body from the `createRun` endpoint you are using and then passing it as an output variable? The complex part would be to handle multiple outputs when several pipelines are triggered at same time.

(here is the endpoint doc https://docs.microsoft.com/fr-fr/azure/data-factory/quickstart-create-data-factory-rest-api#create-pipeline-run)

**Comment by liprec** [comment]
I have just uploaded a new version (V2.2.0) which contains this enhancement.
