### ISSUE TITLE
Is it possible to wait for the pipeline run status before declaring the task a success?

### ISSUE THREAD

**Issue by Jaffacakes82** [liprec/vsts-publish-adf#38]
Hello,

I want to incorporate this task into a release definition that allows my data QA team to control when data is deployed through environments.

After triggering a pipeline run, is it possible to wait for the result of that pipeline run and determining success of the task based on that result?

Thanks for doing an awesome job!

**Comment by liprec** [comment]
At this moment the task only triggers a pipeline run and is not waiting for that run to complete. I have plans to add such a task to wait and poll the task run.

**Comment by LianaN** [comment]
Indeed it would be a very useful enhancement.

**Comment by chrisbilsoe** [comment]
Any news on this? Would be much appreciated!

**Comment by liprec** [comment]
I am still looking what is the best way to do this: either as option in the task or define a release gate (https://docs.microsoft.com/en-us/azure/devops/pipelines/release/approvals/gates?view=azure-devops).
My preference is to the gate, btw.

**Comment by liprec** [comment]
The latest version (2.3.2) has now a gate [https://docs.microsoft.com/en-us/azure/devops/pipelines/release/approvals/gates?view=azure-devops](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/approvals/gates?view=azure-devops&WT.mc_id=DP-MVP-5003419) task to query running trigger/pipeline runs in a serverless environment.

**Comment by dvasdekis** [comment]
> The latest version (2.3.2) has now a gate [https://docs.microsoft.com/en-us/azure/devops/pipelines/release/approvals/gates?view=azure-devops](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/approvals/gates?view=azure-devops&WT.mc_id=DP-MVP-5003419) task to query running trigger/pipeline runs in a serverless environment.

Hi @liprec , thank you for a fantastic module.

I'm wondering if there's any instructions or documentation available about using the gate task as you describe. I'm searching around but can't find any.
Thank you!

**Comment by liprec** [comment]
Hi @dvasdekis,
You can find the documentation here: https://azurebi-docs.jppp.org/vsts-extensions/azure-data-factory-query.html?tabs=classic%2Cdocs-open

Initially when this task was released the `yml` definition didn't support the 're-evaluation' option, but I have no idea if that has changed recently.
