### ISSUE TITLE
Dependencies between the pipelines that causes to delete error

### ISSUE THREAD

**Issue by sriranawaka** [liprec/vsts-publish-adf#42]

**Comment by liprec** [comment]
All the tasks do not respect dependencies out of the box and you should create it yourself with the use of multiple tasks and the logic naming/filters while deleting your pipelines.

**Comment by liprec** [comment]
The current version (v2.3.3) contains support for the detection of pipeline/linked service dependencies in combination of parallel task execution. You can add `detectDependancy: true` to your pipeline definition to enable the detection.
