### ISSUE TITLE
Deployment of new pipeline is failing first time

### ISSUE THREAD

**Issue by khanaman22** [liprec/vsts-publish-adf#43]
Hi,
The first time deployment of new pipeline using ADF deployment task is failing however the same task works fine in second attempt.
[error]Error deploying '<Nameofpipeline>' pipeline : {"error":{"code":"BadRequest","message":"The document creation or update failed because of invalid reference '<Nameofnewpipeline>'
Thanks
Aman

**Comment by khanaman22** [comment]
Can anyone please suggest on the issue

**Comment by liprec** [comment]
Hi @khanaman22 ,

Sorry for the delay, but can it be that the pipeline is referencing another pipeline?

-JP

**Comment by khanaman22** [comment]
Hi @liprec 
Yes we are using another pipeline reference in pipeline.
Thanks
Aman.
