### ISSUE TITLE
Trigger pipeline task doesn't find pipelines when there are many pipelines.

### ISSUE THREAD

**Issue by nickperrott** [liprec/vsts-publish-adf#44]
Hi,  thanks for providing these tasks, they are saving me a lot of work!

We have a DTAP ADF setup in DevOps with a release pipeline that deploys from dev -> test -> acc -> prod.   One issue that I have experienced, is that at any point in time, we may have manually enabled/disabled some triggers in test,a cc or propd, and we want the status of the triggers, i.e. whether they are startted or stopped to be preserved when a deployment happens.

I have implemented this in a bit of a roun-about way as I don't yet know much about creating Devops tasks.   I have created two ADF pipelines.   A Push triggers pipeline, which uses the ADF REST api to get the current state of all the trigegrs in the specified DF and writes it to the blob storage.  Then I have a pipeline ADF Pop triggers, which reasds the presevred state and starts/stops the trigegrs as appropriate to restore that state.

I then planned to use you Devops task to trigger the appropriate ADF pipeline at the appropriate plaxces in my release pipeline.  Unfortunately, it doesn't find my ADF pipleines.  I have had a small look at your code, but don't really have time to dig into it, but my guess as to the cause of this issue is that we have rather a lot of pipeliens in our DF and the REST API that gets the pipeline info returns this as blocks and I suspect that you code only ever processes the first block returned.

Hope you can help.  Thanks, Nick.

**Comment by liprec** [comment]
Hi @nickperrott,

Thanks for the call out and indeed the task is not supporting paging yet and it could be possible that there are pipelines missing. I will implement paging in the next version, which will be available in a couple of weeks.

-JP

**Comment by jackmagiera** [comment]
Hello,

I'm sure you are well aware but the pagination issues apply to the triggers list as well. Start/stop all triggers for data factory tops out at 50.

Any update on paging implementation?

**Comment by liprec** [comment]
I have just uploaded a new version (V2.2.0) which contains a fix for this bug.
