### ISSUE TITLE
QUESTIONS RE: Azure Data Factory Delete Items & Azure Data Factory Deployment Tasks

### ISSUE THREAD

**Issue by kingua** [liprec/vsts-publish-adf#46]
**Delete**
Do the filters for the delete task require either * (for all), <blank> for none, or being explicit about the named resources you wish to delete?  Is thre any way to do an 'intelligent' filter to determine what resources are no longer in the ARM template and, therefore, delete them, vs. having to be specific?

**Deploy**
When using the Microsoft recommended Resource Group Update task, we can override template params.  It doesn't look like your deploy task allows for this.  Would one generate and tranform the ARM templates for CI/CD through a different means and then consume those with this task?

Thanks!

**Comment by liprec** [comment]
The tasks only use the input provided when the pipeline is running. Is doesn't look at ARM templates.
The idea behind the task is that you have your definitions inside your code repository and use that for deployment.
