### ISSUE TITLE
The document cannot be deleted since it is referenced by

### ISSUE THREAD

**Issue by javabeanuser** [liprec/vsts-publish-adf#54]
Dear, 
There is a problem with references.
If pipeline is used in other pipeline, that cannot be deleted.
Log file is attached:
[Log.log](https://github.com/liprec/vsts-publish-adf/files/4426014/Log.log)

Best Regards, 
Sergey.

**Comment by liprec** [comment]
The tasks doesn't determine any dependencies between pipelines.
If there is dependency, you have to implement the order of when a pipeline is deleted by yourself. 
This can be by eg. prefixing the pipeline names or by splitting the pipeline and use multiple tasks to delete the pipelines in the correct order.

**Comment by NowinskiK** [comment]
hey guys, I'm not sure if you both aware, but I created Custom Task for Azure DevOps Pipeline which is free of such limitations: [DataFactoryTools](https://marketplace.visualstudio.com/items?itemName=SQLPlayer.DataFactoryTools)  
@liprec, forgive me for pointing here to another tool, but I believe it's worth mentioning.

**Comment by liprec** [comment]
The current version (v2.3.3) contains support for the detection of pipeline/linked service dependencies in combination of parallel task execution. You can add `detectDependancy: true` to your pipeline definition to enable the detection.
