### ISSUE TITLE
Tooltip for Azure Data Factory Trigger task refers to deleting the trigger

### ISSUE THREAD

**Issue by andyworsley** [liprec/vsts-publish-adf#56]
The Azure Data Factory Trigger task is to "Start/stop an Azure Data Factory trigger". However, when you look at the tooltip for the Trigger Filter setting, it refers to which triggers to _delete_. This should be which ones to toggle.

![image](https://user-images.githubusercontent.com/1595450/79684793-04dd3800-822c-11ea-919f-1d52732c2423.png)

**Comment by liprec** [comment]
Thanks for your feedback and it is fixed in the latest version (2.3.2)
