### ISSUE TITLE
Resume / re-run from failed activity of a pipeline

### ISSUE THREAD

**Issue by KTEJ0605** [liprec/vsts-publish-adf#58]
We have a situation where we wanted to trigger the pipeline from the failed activity. How can we achieve using this module?

**Comment by liprec** [comment]
If you know which pipelines to trigger again, you can use the Pipeline Trigger task.
There is no task to get which pipeline runs are failed.

**Comment by KTEJ0605** [comment]
Hi @liprec - Thanks for your reply. We know the name of the pipeline. But, would it be able to trigger from where it left off?
