### ISSUE TITLE
Azure Datafactory Deployment Task is not working in Releases pipeline

### ISSUE THREAD

**Issue by kumarro2** [liprec/vsts-publish-adf#63]
Last week it was successfully completed (Version: 2.2.1) .

This week getting below error(Current Version: 2.3.2)

##[error]Error deploying '' trigger : {"error":{"code":"TriggerEnabledCannotUpdate","message":"Cannot update enabled Trigger; the trigger needs to be disabled first. ","target":null,"details":null}}

**Comment by liprec** [comment]
Thanks for the feedback and it look to me that the trigger you are trying to enable is already enabled.
The latest version has a fix related to the trigger filter that was not correctly applied, so is it possible that in a previous step this trigger should be disabled and isn't? Or is the filter option including to much triggers?

**Comment by kumarro2** [comment]
Yes, we have Stop the trigger in first Task(Azure Data Factory Trigger) and then start the trigger in Last Task((Azure Data Factory Trigger)), We are getting above error in second Task (Azure Data Factory Deployment).

**Comment by liprec** [comment]
So probably the forst task is not stopping a trigger that is included in the last task. If you look in the logging of the task, you see the number of triggers that the task has found to start/stop.
If there are to many triggers, please take a look at the filter option if that has a correct regular expression to include all required triggers.

**Comment by kumarro2** [comment]
We haven't done any changes in Tasks and it was success last week without any issue.

**Comment by liprec** [comment]
This weekend a new version I released a new version with a fix related to the trigger filter that was not correctly applied.
So it looks that this fix is causing the different behavior between now and last week.

**Comment by kumarro2** [comment]
yes i can see the version difference, So how we can fix this ? Do we have to use another task for similar process or need to get back to previous version?

**Comment by liprec** [comment]
In the new version the filter option is a regular expression that is applied to the name of the triggers. And probably the expression used in the start task is including a trigger that is already enabled and cannot start again.

**Comment by 637942** [comment]
Hi @liprec, the actual issue is with the later release of trigger filter regression.

2021-01-05T05:59:48.2119125Z (node:2796) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): SyntaxError: Invalid regular expression: /*/: Nothing to repeat


The expression is not working like before.

YAML:

steps:
- task: liprec.vsts-publish-adf.toggle-adf-trigger.toggle-adf-trigger@2
  displayName: 'Toggle trigger(s) in sampleprodadf
  inputs:
    azureSubscription: Sample
    ResourceGroupName: 'SAMPLE-PROD-RG'
    DatafactoryName: sampleprodadf
    TriggerFilter: '*'
    TriggerStatus: stop

Let us know for more inputs

**Comment by liprec** [comment]
Sorry, finally I see what is going wrong: please remove the TriggerFilter line as the '*' definition is not working correctly. Will add the correct error handling in a next release.

**Comment by 637942** [comment]
Hi @liprec , i have tried the same based on the comments you have provided in the github already. I have left the TriggerFilter as blank but received the exact same error. Basically we need to toggle all the triggers. Is there some other way to tweak the regular expression work?

Please advise.

**Comment by liprec** [comment]
Have you also tried it without the TriggerFilter line? If that is not working I have to look at the code and probably submit a new version.

**Comment by 637942** [comment]
Hi @liprec, i have tried the same in my lower environment now and it works(without trigger filter). Thanks
