### ISSUE TITLE
Stop / Start triggers Syntax Issue

### ISSUE THREAD

**Issue by tushmesh** [liprec/vsts-publish-adf#64]
Getting the below message while stopping the triggers 

Starting: Toggle trigger(s) in xxx(stop)
==============================================================================
Task         : Azure Data Factory Trigger
Description  : Start/stop an Azure Data Factory Trigger
Version      : 2.3.2
Author       : Jan Pieter Posthuma
Help         : [More Information](https://github.com/liprec/vsts-publish-adf)

(node:6056) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): SyntaxError: Invalid regular expression: /*/: Nothing to repeat
Finishing: Toggle trigger(s) in xxx(stop)
==============================================================================

**Comment by liprec** [comment]
Thanks for your feedback. The latest version (2.3.2) has a fix for the trigger filter option that wasn't applied correctly.
Looks like the there is something wrong with the filter expression. Could you check if the filter option to see is a correct regular expression?
And is it possible to share the filter option so I can add a more functional error message?

Thanks

**Comment by tushmesh** [comment]
Here is the snippet

# Stop Triggers
    - task: liprec.vsts-publish-adf.toggle-adf-trigger.toggle-adf-trigger@2
      displayName: 'Toggle trigger(s) in $(deploymentDataFactoryName)(stop)'
      inputs:
        azureSubscription: Development
        ResourceGroupName: $(deploymentResourceGroupName)
        DatafactoryName: $(deploymentDataFactoryName)
        TriggerFilter: '*'
        TriggerStatus: stop
        Throttle: 20

**Comment by liprec** [comment]
Thanks for the snippet: will add a correct error handling in the next version.
For now, you can remove the `TriggerFilter` line as the default (empty) is to toggle all triggers.

**Comment by tushmesh** [comment]
Thank You !!
