### ISSUE TITLE
Incomplete deploy when missing resource

### ISSUE THREAD

**Issue by liviabijelli** [liprec/vsts-publish-adf#66]
When you configure to deploy Dataflow, Dataset, and Pipeline, but your source doesn't have Dataflow artifacts, only Datasets are deployed, and Pipelines are ignored.
Thinking about an automatic Build/Release, you have to configure all the possibilities for further deploys, and it isn't possible with this issue.

**Comment by liprec** [comment]
What is the result of the task in this case? And does Continue on Error (`Continue`) set to true not deploy the datasets and pipelines?

**Comment by liviabijelli** [comment]
Tks for your reply :)
It ends without error but only datasets are really deployed, pipelines are not (skipped).
I saw in the code that it happens because of the conditions order, first datasets (ok), second dataflows (nok), and it finishes before pipeline's condition, I believe it's necessary to create an exception treatment.

**Comment by liprec** [comment]
Thanks for raising this problem and indeed the task just ends without any notice. Will add a warning/error/ignore path when this happens; haven't decided which it should be.

**Comment by liviabijelli** [comment]
if you want a suggestion, at my operation we don't use dataflows too much, datasets and pipelines are more common, so only one of our data factories has dataflows. It won't be good if it raises an error and stops the deployment, just a warning message and keep continuing with the available resources. The reason for not remove the dataflow configuration is for further use without the need of changing Devops configuration.

**Comment by liprec** [comment]
Fixed in v2.4.0
