### ISSUE TITLE
Query ADF runs (via agentless job) fails with authentication errors, pls assist

### ISSUE THREAD

**Issue by rkmNHS** [liprec/vsts-publish-adf#67]
**Hello there,
I am using the Query ADF runs as a task in devops pipeline via agentless job but facing authentication errors as below:**
-----------------------------------------------------------------------------------------------------------------------------------
Response Code: 0 Response: An error was encountered while processing request. Exception: {"error":{"code":"ResourceNotFound","message":"The Resource 'Microsoft.DataFactory/factories/******* ' under resource group '******' was not found. 
For more details please go to https://aka.ms/ARMResourceNotFoundFix"}}
Exception Message: The remote server returned an error: (404) Not Found. (type WebException)
Evaluation of expression 'or(and(eq(count(jsonpath('$.value[*]')), 0), eq(false, false)), and(ne(count(jsonpath('$.value[*]')), 0), eq(false, true)))' failed.
Exception Message: Error parsing API response into a JSON object. (type DistributedTaskException)
------------------------------------------------------------------------------------------------------------------------------------
Though resource group and adf PIPELINE are correct and do exist and able to run the same in one the task prior to this one.
Please help and feel free to ask for any missing information here. Thanks in advance. Cheers

**Comment by liprec** [comment]
If I look at the error message it seems that the Data Factory is not found in the given resource group. Can you validate that the service principal of the connection can access the data factory? And that there are no typos in the resource group/factory?

**Comment by rkmNHS** [comment]
Hi,

I have given the SP exclusive contributor role and now error have been modified as :

2021-03-19T16:58:21.8893147Z ##[error]Error login in to Azure. Please check the Service Configuration. Error: Failed to acquire token for application with the provided secret.
Error: Get Token request returned http error: 401 and server response: {"error":"invalid_client","error_description":"AADSTS7000215: Invalid client secret is provided.\r\nTrace ID: 58654e2c-8c36-43c3-ab9b-75017e382d00\r\nCorrelation ID: 4575063b-d863-4ce9-a3de-f8744ec16c33\r\nTimestamp: 2021-03-19 16:58:21Z","error_codes":[7000215],"timestamp":"2021-03-19 16:58:21Z","trace_id":"58654e2c-8c36-43c3-ab9b-75017e382d00","correlation_id":"4575063b-d863-4ce9-a3de-f8744ec16c33","error_uri":https://login.microsoftonline.com/error?code=7000215}.
2021-03-19T16:58:21.8908145Z ##[error]Unhandled: Azure clients require credentials.
2021-03-19T16:58:21.9022747Z ##[section]Finishing: Toggle trigger(s) in ADFdevopsPipeline01

Thanks,

**Comment by rkmNHS** [comment]
After adding ADF contributor role to SP now able to fetch the ADF details but while running  following error pops up:
POST https://management.azure.com//subscriptions/1e543650-5458-44ea-a3b1-35a6d0d92cc9/resourceGroups/nhsuk-mssql-core/providers/Microsoft.DataFactory/factories/ADFdevopsPipeline01/queryPipelineRuns?api-version=2018-06-01
Request body: {
  "filters": [
    {
      "operand": "Status",
      "operator": "In",
      "values": [
        "Cancelled",
        "Failed",
        "InProgress",
        "Queued"
      ]
    },
    {
      "operand": "LatestOnly",
      "operator": "Equals",
      "values": [
        true
      ]
    }
  ],
  "lastUpdatedAfter": "2000-01-01T00:00:00Z",
  "lastUpdatedBefore": "2199-12-31T00:00:00Z"
}
				Response Code: OK
				Response: {
  "value": [
    {
      "id": "/SUBSCRIPTIONS/1E543650-5458-44EA-A3B1-35A6D0D92CC9/RESOURCEGROUPS/NHSUK-MSSQL-CORE/PROVIDERS/MICROSOFT.DATAFACTORY/FACTORIES/ADFDEVOPSPIPELINE01/pipelineruns/eb8c25d3-e3af-4bdd-a712-0d106526c2de",
      "runId": "eb8c25d3-e3af-4bdd-a712-0d106526c2de",
      "debugRunId": null,
      "runGroupId": "eb8c25d3-e3af-4bdd-a712-0d106526c2de",
      "pipelineName": "pipeline1",
      "parameters": {},
      "invokedBy": {
        "id": "3d0da486491a47e694da44a6fa37f9b0",
        "name": "Manual",
        "invokedByType": "Manual"
      },
      "runStart": "2021-03-18T15:34:52.3880028Z",
      "runEnd": "2021-03-18T15:34:53.5159139Z",
      "durationInMs": 1127,
      "status": "Failed",
      "message": "ErrorCode=InvalidTemplate, ErrorMessage=The template validation failed: 'The action(s) 'Call failing pipeline' referenced by 'inputs' in action 'ExecuteWeb1' are not defined in the template",
      "lastUpdated": "2021-03-18T15:34:53.5159139Z",
      "annotations": [],
      "runDimension": {},
      "isLatest": true
    },
    {
      "id": "/SUBSCRIPTIONS/1E543650-5458-44EA-A3B1-35A6D0D92CC9/RESOURCEGROUPS/NHSUK-MSSQL-CORE/PROVIDERS/MICROSOFT.DATAFACTORY/FACTORIES/ADFDEVOPSPIPELINE01/pipelineruns/e1677a47-a6c0-49a1-b5c4-9988d89dce7e",
      "runId": "e1677a47-a6c0-49a1-b5c4-9988d89dce7e",
      "debugRunId": null,
      "runGroupId": "e1677a47-a6c0-49a1-b5c4-9988d89dce7e",
      "pipelineName": "pipeline1",
      "parameters": {},
      "invokedBy": {
        "id": "026cadb4167c4e9c8717d471e725e7a8",
        "name": "Manual",
        "invokedByType": "Manual"
      },
      "runStart": "2021-03-18T15:50:23.9987574Z",
      "runEnd": "2021-03-18T15:50:24.6215771Z",
      "durationInMs": 622,
      "status": "Failed",
      "message": "ErrorCode=InvalidTemplate, ErrorMessage=Unable to parse expression 'type'",
      "lastUpdated": "2021-03-18T15:50:24.6215771Z",
      "annotations": [],
      "runDimension": {},
      "isLatest": true
    },
    {
      "id": "/SUBSCRIPTIONS/1E543650-5458-44EA-A3B1-35A6D0D92CC9/RESOURCEGROUPS/NHSUK-MSSQL-CORE/PROVIDERS/MICROSOFT.DATAFACTORY/FACTORIES/ADFDEVOPSPIPELINE01/pipelineruns/6041ea5e-dceb-48f8-b2c2-e437c7094f1c",
      "runId": "6041ea5e-dceb-48f8-b2c2-e437c7094f1c",
      "debugRunId": null,
      "runGroupId": "6041ea5e-dceb-48f8-b2c2-e437c7094f1c",
      "pipelineName": "pipeline1",
      "parameters": {},
      "invokedBy": {
        "id": "970f8aa1d4cb425e972b9ad3fb9688e2",
        "name": "Manual",
        "invokedByType": "Manual"
      },
      "runStart": "2021-03-18T15:52:29.0686111Z",
      "runEnd": "2021-03-18T15:52:29.6786958Z",
      "durationInMs": 610,
      "status": "Failed",
      "message": "ErrorCode=InvalidTemplate, ErrorMessage=Unable to parse expression 'type'",
      "lastUpdated": "2021-03-18T15:52:29.6786958Z",
      "annotations": [],
      "runDimension": {},
      "isLatest": true
    },
    {
      "id": "/SUBSCRIPTIONS/1E543650-5458-44EA-A3B1-35A6D0D92CC9/RESOURCEGROUPS/NHSUK-MSSQL-CORE/PROVIDERS/MICROSOFT.DATAFACTORY/FACTORIES/ADFDEVOPSPIPELINE01/pipelineruns/f64636f9-fbdb-470d-a0ca-6e825e0ee7bd",
      "runId": "f64636f9-fbdb-470d-a0ca-6e825e0ee7bd",
      "debugRunId": null,
      "runGroupId": "f64636f9-fbdb-470d-a0ca-6e825e0ee7bd",
      "pipelineName": "pipeline1",
      "parameters": {},
      "invokedBy": {
        "id": "11faed4f1f0e4dd5ac366d93dcde9dd5",
        "name": "Manual",
        "invokedByType": "Manual"
      },
      "runStart": "2021-03-18T16:11:39.3433207Z",
      "runEnd": "2021-03-18T16:11:39.8800342Z",
      "durationInMs": 536,
      "status": "Failed",
      "message": "ErrorCode=InvalidTemplate, ErrorMessage=Unable to parse expression 'type'",
      "lastUpdated": "2021-03-18T16:11:39.8800342Z",
      "annotations": [],
      "runDimension": {},
      "isLatest": true
    },
    {
      "id": "/SUBSCRIPTIONS/1E543650-5458-44EA-A3B1-35A6D0D92CC9/RESOURCEGROUPS/NHSUK-MSSQL-CORE/PROVIDERS/MICROSOFT.DATAFACTORY/FACTORIES/ADFDEVOPSPIPELINE01/pipelineruns/d6101a83-cc24-40ce-986c-cd6c3048c8e0",
      "runId": "d6101a83-cc24-40ce-986c-cd6c3048c8e0",
      "debugRunId": null,
      "runGroupId": "d6101a83-cc24-40ce-986c-cd6c3048c8e0",
      "pipelineName": "pipeline1",
      "parameters": {},
      "invokedBy": {
        "id": "5f6475dff5704e66800a003dd9327282",
        "name": "Manual",
        "invokedByType": "Manual"
      },
      "runStart": "2021-03-18T16:14:02.7614563Z",
      "runEnd": "2021-03-18T16:14:03.376104Z",
      "durationInMs": 614,
      "status": "Failed",
      "message": "ErrorCode=InvalidTemplate, ErrorMessage=The template validation failed: 'The action(s) 'Call failing pipeline' referenced by 'inputs' in action 'ExecuteWeb1' are not defined in the template",
      "lastUpdated": "2021-03-18T16:14:03.376104Z",
      "annotations": [],
      "runDimension": {},
      "isLatest": true
    },
    {
      "id": "/SUBSCRIPTIONS/1E543650-5458-44EA-A3B1-35A6D0D92CC9/RESOURCEGROUPS/****/PROVIDERS/MICROSOFT.DATAFACTORY/FACTORIES/ADFDEVOPSPIPELINE01/pipelineruns/67d1b20f-83df-4960-b6cf-859b98d7275d",
      "runId": "67d1b20f-83df-4960-b6cf-859b98d7275d",
      "debugRunId": null,
      "runGroupId": "67d1b20f-83df-4960-b6cf-859b98d7275d",
      "pipelineName": "pipeline1",
      "parameters": {},
      "invokedBy": {
        "id": "ffdca1ed501b49ba9e11cf5603154ca1",
        "name": "Manual",
        "invokedByType": "Manual"
      },
      "runStart": "2021-03-18T17:13:00.1602023Z",
      "runEnd": "2021-03-18T17:13:18.3149717Z",
      "durationInMs": 18154,
      "status": "Failed",
      "message": "Operation on target Web1_copy1 failed: <!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01//EN\"\"http://www.w3.org/TR/html4/strict.dtd\">
<HTML><HEAD><TITLE>Service Unavailable</TITLE>
<META HTTP-EQUIV=\"Content-Type\" Content=\"text/html; charset=us-ascii\"></HEAD>
<BODY><h2>Service Unavailable</h2>
<hr><p>HTTP Error 503. The service is unavailable.</p>
</BODY></HTML>
",
      "lastUpdated": "2021-03-18T17:13:18.3149717Z",
      "annotations": [],
      "runDimension": {},
      "isLatest": true
    }
  ]
}
				Evaluation of expression 'or(and(eq(count(jsonpath('$.value[*]')), 0), eq(false, false)), and(ne(count(jsonpath('$.value[*]')), 0), eq(false, true)))' failed.

**Comment by rkmNHS** [comment]
In debug mode the error is as below:
POST https://management.azure.com//subscriptions/1e543650-5458-44ea-a3b1-35a6d0d92cc9/resourceGroups/nhsuk-mssql-core/providers/Microsoft.DataFactory/factories/ADFdevopsPipeline01/queryPipelineRuns?api-version=2018-06-01
Request body: {
  "filters": [
    {
      "operand": "Status",
      "operator": "In",
      "values": [
        "Cancelled",
        "Failed",
        "InProgress",
        "Queued"
      ]
    },
    {
      "operand": "LatestOnly",
      "operator": "Equals",
      "values": [
        true
      ]
    }
  ],
  "lastUpdatedAfter": "2000-01-01T00:00:00Z",
  "lastUpdatedBefore": "2199-12-31T00:00:00Z"
}
				Response Code: OK
				Response: {
  "value": [
    {
      "id": "/SUBSCRIPTIONS/1E543650-5458-44EA-A3B1-35A6D0D92CC9/RESOURCEGROUPS/NHSUK-MSSQL-CORE/PROVIDERS/MICROSOFT.DATAFACTORY/FACTORIES/ADFDEVOPSPIPELINE01/pipelineruns/eb8c25d3-e3af-4bdd-a712-0d106526c2de",
      "runId": "eb8c25d3-e3af-4bdd-a712-0d106526c2de",
      "debugRunId": null,
      "runGroupId": "eb8c25d3-e3af-4bdd-a712-0d106526c2de",
      "pipelineName": "pipeline1",
      "parameters": {},
      "invokedBy": {
        "id": "3d0da486491a47e694da44a6fa37f9b0",
        "name": "Manual",
        "invokedByType": "Manual"
      },
      "runStart": "2021-03-18T15:34:52.3880028Z",
      "runEnd": "2021-03-18T15:34:53.5159139Z",
      "durationInMs": 1127,
      "status": "Failed",
      "message": "ErrorCode=InvalidTemplate, ErrorMessage=The template validation failed: 'The action(s) 'Call failing pipeline' referenced by 'inputs' in action 'ExecuteWeb1' are not defined in the template",
      "lastUpdated": "2021-03-18T15:34:53.5159139Z",
      "annotations": [],
      "runDimension": {},
      "isLatest": true
    },
    {
      "id": "/SUBSCRIPTIONS/1E543650-5458-44EA-A3B1-35A6D0D92CC9/RESOURCEGROUPS/NHSUK-MSSQL-CORE/PROVIDERS/MICROSOFT.DATAFACTORY/FACTORIES/ADFDEVOPSPIPELINE01/pipelineruns/e1677a47-a6c0-49a1-b5c4-9988d89dce7e",
      "runId": "e1677a47-a6c0-49a1-b5c4-9988d89dce7e",
      "debugRunId": null,
      "runGroupId": "e1677a47-a6c0-49a1-b5c4-9988d89dce7e",
      "pipelineName": "pipeline1",
      "parameters": {},
      "invokedBy": {
        "id": "026cadb4167c4e9c8717d471e725e7a8",
        "name": "Manual",
        "invokedByType": "Manual"
      },
      "runStart": "2021-03-18T15:50:23.9987574Z",
      "runEnd": "2021-03-18T15:50:24.6215771Z",
      "durationInMs": 622,
      "status": "Failed",
      "message": "ErrorCode=InvalidTemplate, ErrorMessage=Unable to parse expression 'type'",
      "lastUpdated": "2021-03-18T15:50:24.6215771Z",
      "annotations": [],
      "runDimension": {},
      "isLatest": true
    },
    {
      "id": "/SUBSCRIPTIONS/1E543650-5458-44EA-A3B1-35A6D0D92CC9/RESOURCEGROUPS/NHSUK-MSSQL-CORE/PROVIDERS/MICROSOFT.DATAFACTORY/FACTORIES/ADFDEVOPSPIPELINE01/pipelineruns/6041ea5e-dceb-48f8-b2c2-e437c7094f1c",
      "runId": "6041ea5e-dceb-48f8-b2c2-e437c7094f1c",
      "debugRunId": null,
      "runGroupId": "6041ea5e-dceb-48f8-b2c2-e437c7094f1c",
      "pipelineName": "pipeline1",
      "parameters": {},
      "invokedBy": {
        "id": "970f8aa1d4cb425e972b9ad3fb9688e2",
        "name": "Manual",
        "invokedByType": "Manual"
      },
      "runStart": "2021-03-18T15:52:29.0686111Z",
      "runEnd": "2021-03-18T15:52:29.6786958Z",
      "durationInMs": 610,
      "status": "Failed",
      "message": "ErrorCode=InvalidTemplate, ErrorMessage=Unable to parse expression 'type'",
      "lastUpdated": "2021-03-18T15:52:29.6786958Z",
      "annotations": [],
      "runDimension": {},
      "isLatest": true
    },
    {
      "id": "/SUBSCRIPTIONS/1E543650-5458-44EA-A3B1-35A6D0D92CC9/RESOURCEGROUPS/NHSUK-MSSQL-CORE/PROVIDERS/MICROSOFT.DATAFACTORY/FACTORIES/ADFDEVOPSPIPELINE01/pipelineruns/f64636f9-fbdb-470d-a0ca-6e825e0ee7bd",
      "runId": "f64636f9-fbdb-470d-a0ca-6e825e0ee7bd",
      "debugRunId": null,
      "runGroupId": "f64636f9-fbdb-470d-a0ca-6e825e0ee7bd",
      "pipelineName": "pipeline1",
      "parameters": {},
      "invokedBy": {
        "id": "11faed4f1f0e4dd5ac366d93dcde9dd5",
        "name": "Manual",
        "invokedByType": "Manual"
      },
      "runStart": "2021-03-18T16:11:39.3433207Z",
      "runEnd": "2021-03-18T16:11:39.8800342Z",
      "durationInMs": 536,
      "status": "Failed",
      "message": "ErrorCode=InvalidTemplate, ErrorMessage=Unable to parse expression 'type'",
      "lastUpdated": "2021-03-18T16:11:39.8800342Z",
      "annotations": [],
      "runDimension": {},
      "isLatest": true
    },
    {
      "id": "/SUBSCRIPTIONS/1E543650-5458-44EA-A3B1-35A6D0D92CC9/RESOURCEGROUPS/NHSUK-MSSQL-CORE/PROVIDERS/MICROSOFT.DATAFACTORY/FACTORIES/ADFDEVOPSPIPELINE01/pipelineruns/d6101a83-cc24-40ce-986c-cd6c3048c8e0",
      "runId": "d6101a83-cc24-40ce-986c-cd6c3048c8e0",
      "debugRunId": null,
      "runGroupId": "d6101a83-cc24-40ce-986c-cd6c3048c8e0",
      "pipelineName": "pipeline1",
      "parameters": {},
      "invokedBy": {
        "id": "5f6475dff5704e66800a003dd9327282",
        "name": "Manual",
        "invokedByType": "Manual"
      },
      "runStart": "2021-03-18T16:14:02.7614563Z",
      "runEnd": "2021-03-18T16:14:03.376104Z",
      "durationInMs": 614,
      "status": "Failed",
      "message": "ErrorCode=InvalidTemplate, ErrorMessage=The template validation failed: 'The action(s) 'Call failing pipeline' referenced by 'inputs' in action 'ExecuteWeb1' are not defined in the template",
      "lastUpdated": "2021-03-18T16:14:03.376104Z",
      "annotations": [],
      "runDimension": {},
      "isLatest": true
    },
    {
      "id": "/SUBSCRIPTIONS/1E543650-5458-44EA-A3B1-35A6D0D92CC9/RESOURCEGROUPS/NHSUK-MSSQL-CORE/PROVIDERS/MICROSOFT.DATAFACTORY/FACTORIES/ADFDEVOPSPIPELINE01/pipelineruns/67d1b20f-83df-4960-b6cf-859b98d7275d",
      "runId": "67d1b20f-83df-4960-b6cf-859b98d7275d",
      "debugRunId": null,
      "runGroupId": "67d1b20f-83df-4960-b6cf-859b98d7275d",
      "pipelineName": "pipeline1",
      "parameters": {},
      "invokedBy": {
        "id": "ffdca1ed501b49ba9e11cf5603154ca1",
        "name": "Manual",
        "invokedByType": "Manual"
      },
      "runStart": "2021-03-18T17:13:00.1602023Z",
      "runEnd": "2021-03-18T17:13:18.3149717Z",
      "durationInMs": 18154,
      "status": "Failed",
      "message": "Operation on target Web1_copy1 failed: <!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01//EN\"\"http://www.w3.org/TR/html4/strict.dtd\">
<HTML><HEAD><TITLE>Service Unavailable</TITLE>
<META HTTP-EQUIV=\"Content-Type\" Content=\"text/html; charset=us-ascii\"></HEAD>
<BODY><h2>Service Unavailable</h2>
<hr><p>HTTP Error 503. The service is unavailable.</p>
</BODY></HTML>
",
      "lastUpdated": "2021-03-18T17:13:18.3149717Z",
      "annotations": [],
      "runDimension": {},
      "isLatest": true
    }
  ]
}
				Parsing expression: <or(and(eq(count(jsonpath('$.value[*]')), 0), eq(false, false)), and(ne(count(jsonpath('$.value[*]')), 0), eq(false, true)))>
				or
				(
				..and
				(
				....eq
				..(
				......count
				....(
				........jsonpath
				......(
				..........'$.value[*]'
				........)
				......)
				......,
				......0
				....)
				....,
				....eq
				..(
				......False
				......,
				......False
				....)
				..)
				..,
				..and
				(
				....ne
				..(
				......count
				....(
				........jsonpath
				......(
				..........'$.value[*]'
				........)
				......)
				......,
				......0
				....)
				....,
				....eq
				..(
				......False
				......,
				......True
				....)
				..)
				)
				Evaluating: or(and(eq(count(jsonpath('$.value[*]')), 0), eq(False, False)), and(ne(count(jsonpath('$.value[*]')), 0), eq(False, True)))
				Evaluating or:
				..Evaluating and:
				....Evaluating eq:
				......Evaluating count:
				........Evaluating jsonpath:
				..........Evaluating String:
				..........=> '$.value[*]'
				........=> Array
				......=> 6
				......Evaluating Number:
				......=> 0
				....=> False
				..=> False
				..Evaluating and:
				....Evaluating ne:
				......Evaluating count:
				........Evaluating jsonpath:
				..........Evaluating String:
				..........=> '$.value[*]'
				........=> Array
				......=> 6
				......Evaluating Number:
				......=> 0
				....=> True
				....Evaluating eq:
				......Evaluating Boolean:
				......=> False
				......Evaluating Boolean:
				......=> True
				....=> False
				..=> False
				=> False
				Expanded: or(and(eq(6, 0), eq(False, False)), and(ne(6, 0), eq(False, True)))
				Result: False
				Evaluation of expression 'or(and(eq(count(jsonpath('$.value[*]')), 0), eq(false, false)), and(ne(count(jsonpath('$.value[*]')), 0), eq(false, true)))' failed.

**Comment by liprec** [comment]
Looking at your error messages I see 503 errors with the 'Web1_copy1' task: looks like there is an issue with this task in the pipeline.
And the output message can be a bit strange and overwhelming, but the last bit gives you the clue: 

```
Expanded: or(and(eq(6, 0), eq(False, False)), and(ne(6, 0), eq(False, True)))
Result: False
Evaluation of expression 'or(and(eq(count(jsonpath('$.value[*]')), 0), eq(false, false)), and(ne(count(jsonpath('$.value[*]')), 0), eq(false, true)))' failed.
```

The result of the expression to see if there are no errors is `False` and therefor the gate task has `failed`.
