### ISSUE TITLE
Azure Data Factory Deployment works by service connection configured with MSI authentication?

### ISSUE THREAD

**Issue by JordiPL** [liprec/vsts-publish-adf#69]
I change the service connection with service principal authentication by other service connection with MSI authentication over the subscription, when create the release and runs the task Azure Data Factory Deployment it stop and show this log:

![image](https://user-images.githubusercontent.com/74967499/115776533-83773300-a3b4-11eb-9bde-79475be004c2.png)

Thanks for yours answers. 

Regards.

**Comment by liprec** [comment]
Thank for the feedback and currently is it not supported.
But I will take a look if it is possible to implement this feature in a next version.

**Comment by liprec** [comment]
Added in v2.4.0
