### ISSUE TITLE
Dataset Filter and Linked Services Filter in Azure Devops - Releases - Azure Data Factory Delete Items not working as expected

### ISSUE THREAD

**Issue by adamsxs** [liprec/vsts-publish-adf#71]
I'm using a `*` filter to delete all objects as the tooltip suggests, but in the subsequent task log it doesn’t find any datasets or linked services. It does however find and delete triggers, pipelines, and data flows. Running on version 2.3.3. The logs do show a line for `2021-07-13T16:30:59.7141410Z Found 0 dataflow(s)`, but nothing similar for Linked Services or Datasets.

Other things I've tried:
- If I have a dataset named `my_dataset` in the ADF, putting `my_dataset` as the filter value doesn’t delete the dataset from the ADF. This is not expected.
- Leaving the pipeline filter blank leads to no pipelines getting deleted, as expected.
- Older logs (2020-12-23, version 2.2.2) with the same filter show evidence of datasets and linked services being detected and deleted. This would be the expected behavior.

Thanks in advance for any help on workarounds or solutions I might’ve missed!

[tasklog_7 (1).log](https://github.com/liprec/vsts-publish-adf/files/6810979/tasklog_7.1.log)
![B23af11877d3f46aebe09216310587a8d637588734488644148_ADF_delete_items_filters (1)](https://user-images.githubusercontent.com/40548280/125501492-76e0f6db-67e5-4d6d-af97-0d2250016b03.png)

**Comment by adamsxs** [comment]
Adding logs from version 2.2.2 for comparison to show the expected delete behavior. Id's and other identifying information have been obfuscated. In the menu I don't have the option to change the version to anything other than `2.*`, so simply reverting to the old version is unfortunately not an option.

![ADF_delete_items_filters log v2 2 2](https://user-images.githubusercontent.com/40548280/125502552-efdeb98d-e82a-47cc-81a5-4fee9aae2196.png)

**Comment by liprec** [comment]
Fixed in v2.4.0
