### ISSUE TITLE
'error' error message

### ISSUE THREAD

**Issue by NoudF** [liprec/vsts-publish-adf#74]
Since this morning we are receiving the following error when triggering ADF pipelines:

Starting: Trigger ADF Pipelines
.==============================================================================
Task         : Azure Data Factory Trigger Pipeline
Description  : Trigger Azure Data Factory V2 Pipelines
Version      : 2.4.0
Author       : Jan Pieter Posthuma
Help         : [More Information](https://github.com/liprec/vsts-publish-adf)
.==============================================================================
##[error]Error calling DataFactory/pipelines API. Error: Cannot read property 'value' of undefined.
##[error]Error retrieving pipelines: Error:  undefined
Finishing: Trigger ADF Pipelines

When looking at the repo, we saw that there has been an update yesterday, which suposedly fixes this issue. However, this has for us now only been introduced.

On version 2.3.3 everything worked perfectly fine.

**Comment by liprec** [comment]
Sorry about this, but a fix is being released in the next couple of hours, v2.4.1 that contains a fix for this.

**Comment by liprec** [comment]
Quick update: new release (v.2.4.1) has been published to the marketplace.

**Comment by NoudF** [comment]
Thanks for the fix and quick response!
