### ISSUE TITLE
Azure Devops Pipeline Warning

### ISSUE THREAD

**Issue by laurencewells** [liprec/vsts-publish-adf#76]
Hello Author, I noticed a warning today from Azure Devops Pipeline:

This task uses Node 6 execution handler, which will be deprecated soon. If you are the developer of the task - please consider the migration guideline to Node 10 handler - https://aka.ms/migrateTaskNode10. If you are the user - feel free to reach out to the owners of this task to proceed on migration.

![image](https://user-images.githubusercontent.com/24591884/142204168-eb46d8e4-d3cd-40ca-b3c5-69e2b4b3eea8.png)

**Comment by liprec** [comment]
Thanks for the feedback and I will update the task any time soon.

**Comment by liprec** [comment]
Tasks is release v2.4.2 which is now available in the marketplace.
