### ISSUE TITLE
Issue while deploying to government clouds

### ISSUE THREAD

**Issue by annapriyajose** [liprec/vsts-publish-adf#79]
@liprec 
We are using the below-mentined tasks in our YAML deployment pipeline
- toggle-adf-trigger@2
- deploy-adf-json@2

These tasks are working fine in the public cloud, but we are getting errors on those tasks while deploying to the GCC environment. 

_##[error]Error login in to Azure. Please check the Service Configuration. Error: Get Token request returned http error: 400 and server response: {"error":"invalid_request","error_description":"AADSTS900382: Confidential Client is not supported in Cross Cloud request_

I think we need to update the ARM service endpoints to be able to accept government clouds too which are currently hardcoded now for public cloud ' url: `https://management.azure.com'
[Search · .azure.com · GitHub](https://github.com/liprec/vsts-publish-adf/search?q=.azure.com)

Refer the documentation for government endpoint - [Azure Resource Manager](https://docs.microsoft.com/en-us/azure/azure-government/compare-azure-government-global-azure#:~:text=Azure%20Resource%20Manager,management.usgovcloudapi.net)

---
#### Document details

⚠ Do not edit this section. It is required for docs.jppp.org ➟ GitHub issue linking.

* document_id=df2f37bb-fec0-4b8e-a348-b14464d9ced1
* document_url=https://azurebi-docs.jppp.org/vsts-extensions/azure-data-factory-trigger.html

**Comment by liprec** [comment]
Please push the PR and I will take a look at it.

**Comment by liprec** [comment]
Supported with the latest version: v2.5
