### ISSUE TITLE
Toggle trigger(s) Start/Stop in ADF through Pipeline

### ISSUE THREAD

**Issue by venusunkara88** [liprec/vsts-publish-adf#98]
Hi @liprec ,

I'm using this task to Start/Stop of my ADF Trigger and somehow im getting this below error. Thanks in Advance.

##[error]Error toggle trigger trigger1 to state start:  Error: {"headers":{"_headersMap":{"cache-control":{"name":"cache-control","value":"no-cache"},"connection":{"name":"connection","value":"close"},...............

![image](https://github.com/liprec/vsts-publish-adf/assets/44004031/a777d098-176e-4a2e-83be-500b06e38315)

Tried in both build(yaml) and release(classic) pipeline.

**Comment by UGangal-Insight** [comment]
need to perform AZ login first
